### ISSUE TITLE
Using Vue for rendering instead of D3

### ISSUE THREAD

**Issue by jnsprnw** [BSA-US/primer#14]
Hey hey,
you said that you are not totally familiar with mixing Vue and D3. That’s why I would recommend making some changes to how things are rendered in the current version.

I had good experience with rendering everthing in Vue. The advantage is that you are not changing the dom from outside the virtual dom. And integrating interaction from the store is also slightly easier.
The idea is that you use D3 just to create the »data« (ie the content of `d` in the edges, for example), pass it to the Vue component and render it there by looping over it like this:
```Vue
<path
  v-for="{ d, foo } in paths"
  :d="d"
  class="links"
  :style="{ strokeWidth: 1, stroke: `rgba(0, 0, 0, ${foo})` }"
/>
```

Did you have reason to not do it that way?

I could give it try once the data flow works for me.

**Comment by replygirl** [comment]
I didn't think to do it that way at first but it makes way more sense. I'm gonna give it a shot tonight because I think it'll make #5 and #6 a lot easier
